"""empty message

Revision ID: 802691ea71dc
Revises: 
Create Date: 2017-08-12 18:09:54.639559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802691ea71dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('status', sa.SmallInteger(), server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'status')
    # ### end Alembic commands ###
